### ISSUE TITLE
Confused tux

### ISSUE THREAD

**Issue by tux314159** [AJR07/Stamford-Notifier#1]
Tux is confused

**Comment by AJR07** [comment]
Ignore this repo im gonna move it

**Comment by tux314159** [comment]
Heheheheheheh

**Comment by AJR07** [comment]
hi

Thank you and have a nice day! This is my personal email account, feel free to contact me further if you have any questions! ***@***.******@***.******@***.******@***.***>) are my main emails

From: Isaac ***@***.***>
Date: Sunday, 23 May 2021 at 10:39 PM
To: AJR07-2/Stamford-Notifier ***@***.***>
Cc: AJR ***@***.***>, Comment ***@***.***>
Subject: Re: [AJR07-2/Stamford-Notifier] Confused tux (#1)

Heheheheheheh

**Comment by tux314159** [comment]
Sus

**Comment by AJR07** [comment]
:)

**Comment by AJR07** [comment]
HI TUX!

**Comment by tux314159** [comment]
HALLO NIANNY!!!
:DDDDD
